# listener services that you can opt into for a repository
services:
    app.subscriber.status_change_by_comment_subscriber:
        class: AppBundle\Subscriber\StatusChangeByCommentSubscriber
        arguments:
            - '@app.status_api'
            - '@logger'

    app.subscriber.status_change_on_push_subscriber:
        class: AppBundle\Subscriber\StatusChangeOnPushSubscriber
        arguments:
            - '@app.status_api'

    app.subscriber.needs_review_new_pr_subscriber:
        class: AppBundle\Subscriber\NeedsReviewNewPRSubscriber
        arguments:
            - '@app.status_api'

    app.subscriber.bug_label_new_issue_subscriber:
        class: AppBundle\Subscriber\BugLabelNewIssueSubscriber
        arguments:
            - '@app.status_api'

    app.subscriber.auto_label_pr_from_content_subscriber:
        class: AppBundle\Subscriber\AutoLabelPRFromContentSubscriber
        arguments:
            - '@app.github.cached_labels_api'

    app.subscriber.status_change_by_review_subscriber:
        class: AppBundle\Subscriber\StatusChangeByReviewSubscriber
        arguments:
            - '@app.status_api'
            - '@logger'

    app.subscriber.write_issue_on_merged_feature:
        class: AppBundle\Subscriber\WriteIssueOnMergedFeatureSubscriber
        arguments:
            - '@app.github.cached_labels_api'
            - '@app.github.issues_api'
            - 'symfony/symfony-docs'

parameters:
    # point to the main symfony repositories
    repositories:
        symfony/symfony:
            subscribers:
                - app.subscriber.status_change_by_comment_subscriber
                - app.subscriber.status_change_by_review_subscriber
                - app.subscriber.needs_review_new_pr_subscriber
                - app.subscriber.bug_label_new_issue_subscriber
                - app.subscriber.auto_label_pr_from_content_subscriber
                - app.subscriber.write_issue_on_merged_feature
            # secret: change_me

        symfony/symfony-docs:
            subscribers:
                - app.subscriber.status_change_by_comment_subscriber
                - app.subscriber.status_change_on_push_subscriber
                - app.subscriber.status_change_by_review_subscriber
                - app.subscriber.needs_review_new_pr_subscriber
                - app.subscriber.bug_label_new_issue_subscriber
                - app.subscriber.auto_label_pr_from_content_subscriber
            # secret: %symfony_docs_secret%

        # used in a functional test
        weaverryan/symfony:
            subscribers:
                - app.subscriber.status_change_by_comment_subscriber
                - app.subscriber.status_change_on_push_subscriber
                - app.subscriber.status_change_by_review_subscriber
                - app.subscriber.needs_review_new_pr_subscriber
                - app.subscriber.bug_label_new_issue_subscriber
                - app.subscriber.auto_label_pr_from_content_subscriber
