services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Api\Issue\IssueApi: '@App\Api\Issue\NullIssueApi'
    App\Api\Label\LabelApi: '@App\Api\Label\StaticLabelApi'
    App\Api\Milestone\MilestoneApi: '@App\Api\Milestone\StaticMilestoneApi'
    App\Api\PullRequest\PullRequestApi: '@App\Api\PullRequest\NullPullRequestApi'
    App\Api\Status\StatusApi: '@App\Api\Status\NullStatusApi'
