name: Find Reviewer

on:
  repository_dispatch:
    types: [find-reviewer]

jobs:
  find:
    name: Search
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create path
        run: mkdir -p build/reviewer

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-7.4-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-7.4-
            composer-${{ runner.os }}-
            composer-

      - name: Download dependencies
        run: composer install --no-interaction --optimize-autoloader

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: build/reviewer/var
          key: nyholm-git-reviewer

      - name: Checkout GitReviewer repo
        run: |
          mkdir -p build/reviewer/var
          mv build/reviewer/var build/reviewer_tmp
          composer create-project nyholm/git-reviewer build/reviewer
          mv build/reviewer_tmp build/reviewer/var

      - name: Download dependencies
        run: |
          cd build/reviewer
          composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable

      - name: Checkout target repo
        id: target-repo
        run: |
          git clone https://github.com/${{ github.event.client_payload.repository }} build/target/${{ github.event.client_payload.repository }}
          echo "::set-output name=dir::$(pwd)/build/target/${{ github.event.client_payload.repository }}"

      - name: Find branch base
        id: target-base
        run: |
          cd build/reviewer
          BASE=$(./git-reviewer.php pull-request:base ${{ github.event.client_payload.pull_request_number }} ${{ steps.target-repo.outputs.dir }})
          echo "::set-output name=branch::$BASE"

      - name: Checkout branch base
        run: |
          cd ${{ steps.target-repo.outputs.dir }}
          echo ${{ steps.target-base.outputs.branch }}
          git pull
          git checkout ${{ steps.target-base.outputs.branch }}

      - name: Find reviwers
        env:
          GITHUB_TOKEN: ${{ secrets.CARSONPROD_GITHUB_TOKEN }}
        run: |
          cd build/reviewer
          ./git-reviewer.php find ${{ github.event.client_payload.pull_request_number }} ${{ steps.target-repo.outputs.dir }} \
          --after `date +%Y-%m-%d --date="2 year ago"` \
          --ignore-path "src/Symfony/FrameworkBundle/*" \
          --ignore-path "src/Symfony/Bundle/FrameworkBundle/*" \
          --ignore-path "src/**/Tests/*" \
          --ignore-path CHANGELOG*.md \
          --ignore-path UPGRADE*.md \
          --pretty-print > output.json

          cat output.json

      - name: Write comment
        env:
          GITHUB_TOKEN: ${{ secrets.CARSONPROD_GITHUB_TOKEN }}
        run: bin/console app:review:suggest ${{ github.event.client_payload.repository }} ${{ github.event.client_payload.pull_request_number }} ${{ github.event.client_payload.type }} `pwd`/build/reviewer/output.json
